### ISSUE TITLE
experimental environment,  mex-file 

### ISSUE THREAD

**Issue by linmoxiaomo** [pcirujeda/CovGT-3DRegistration-matlab#1]
I run runme.m and met a problem "Matlab has encountered an internal problem and needs to close", which showed by MATLAB crash file. This error was detected while a MEX-file was running. If the MEX-file is not an official MathWorks function, please examine its source code for errors. 

Have you ever encountered this kind of problem? My matlab authorized edition is R2016a in 64-bit operation system, Windows 7.

**Comment by wildanimal7** [comment]
Got the same issue on windows after having compiled the KDTrees folder.
Try Linux, it worked for me like a charm.

**Comment by pcirujeda** [comment]
Thanks for reporting the issue, I just updated the code dependencies to Mathworks' knn searcher object, could you check if it's working for you now?
Cheers
